---
- hosts: localhost
  remote_user: root
  become_method: sudo
  become: yes
  tasks:
    - name: Enable root login
      shell: sudo cp ~/.ssh/authorized_keys /root/.ssh/
      
    - name: Import the public key used by the package management system
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927 state=present
  
    - name: install gnupg
      become: yes
      apt:
        name: gnupg

    - name: add apt key
      become: yes
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc

    - name: add apt repository
      become: yes
      apt_repository:
        repo: deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse
        filename: mongodb-org-4.2.list

    - name: install mongodb
      apt: pkg=mongodb-org state=latest
  
    - name: start mongodb
      service: name=mongod state=started daemon-reload=true
   
