---
- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks: 
  - name: "updating server"
    apt:
      update_cache: yes
 
  - name: "Installing apt dependencies"
    apt:
     name: "{{item}}"
    with_items:
      - python-pip
      - python-dev 
      - libmysqlclient-dev
      - mysql-client
      - mysql-server

  - name: "Installing pip dependencies"
    pip:
      name: MySQL-python
      extra_args: --index=https://pypi.python.org/pypi/

  - name: Create a new database with name 'mysql'
    mysql_db:
      name: mydb
      state: present

  - name: "Creating mysql user"
    mysql_user:
      name: jorge
      password : password
      priv: 'mydb.*:ALL'
      state: present


